apiVersion: v1
kind: Service
metadata:
  name: bookstoreserver
spec:
  selector:
    app: bookstoreserver
  ports:
    - protocol: TCP
      port: 8090        # Port that the service will expose
      targetPort: 8090  # Port on the Pod to forward to
      nodePort: 30007  # Port on the node to forward to
  type: NodePort
